base: &base
  adapter: mysql2
  host: localhost
  encoding: utf8
  reconnect: ture
  timeout: 1000
  pool: 30
  username: root

development:
  <<: *base
  database: rails_gems_tool_dev
  password: 123456

production:
  <<: *base
  database: rails_gems_tool
  password: 123456

test:
  <<: *base
  database: rails_gems_tool_test
  password: 123456